apiVersion: apps/v1
kind: Deployment
metadata:
  name: appt-booking-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appt-booking-api
  template:
    metadata:
      labels:
        app: appt-booking-api
    spec:
      containers:
        - name: springboot
          image: pkdocker3383/appt-booking-api:v1
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: appt-booking-api
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: appt-booking-api