version: '3'
services:
  mongodb:
    image: mongo:4.2.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: $u
      MONGO_INITDB_ROOT_PASSWORD: $p
    env_file:
      - $ef
    ports:
      - "27017:27017"
    volumes:
      - "ok8:/data/db"
      - "./users_init.sh:/docker-entrypoint-initdb.d/users_init.sh:ro"
    networks:
      - network1

networks:
  network1:
    driver: "bridge"
volumes:
  ok8: